


AWSTemplateFormatVersion: '2010-09-09'
Description: create an RDS database with Mysql


Parameters:

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Type: String
    Default: t2.micro
  
  ImageId:
    Type: String
    Default: ami-0e742cca61fb65051
    
  VpcCIDR:
    Type: String
    Description: Please enter the Ip range
    Default: 10.0.0.0/24

  PrivateSubnet1CIDR:
    Type: String
    Description: please enter the Ip range
    Default: 10.0.0.0/24

 
  

Resources:

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
      SubnetId: !Ref PrivateSubnet1

      Tags:
        - Key: Name
          Value: Demoec2  
  
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: Test-Vpc
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PrivateSubnet1CIDR
      AvailabilityZone: !Select [ 0, !GetAZs ]
      VpcId: !Ref MyVpc
      Tags:
         - Key: Name
           Value: Private-TestSubnet1

  
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      
      GroupDescription: My SG with port 22 and 8080 inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080          
          ToPort: 8080
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: EC2-SG
      VpcId: !Ref MyVpc  

  MyDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      
      GroupDescription: My SG with port 22 and 8080 inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
      Tags:
        - Key: Name
          Value: DB-SG
      VpcId: !Ref MyVpc  






