

---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'This template deploys VPC with a pair of public and private subnets.
  '
Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
 
  ImageId:
    Type: String
    Default: ami-0e742cca61fb65051

  InstanceType:
    Type: String
    Default: t2.micro

  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: ap-south-1
    
  VPCCIDR:
    Type: String
    Description: Please enter the IP range (CIDR notation) for this VPC
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/16
    
  PublicSubnetCIDR:
    Type: String
    Description: Please enter the IP address range for the VPC subnet
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.0.0/24
   
  PrivateSubnetCIDR:
    Type: String
    Description: Please enter the IP address range for the VPC subnet
    MinLength: '9'
    MaxLength: '18'
    Default: 10.0.1.0/24
    
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
      SubnetId: !Ref PublicSubnet

      Tags:
        - Key: Name
          Value: Demoec2  
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: Test-Vpc
          
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: Test-IGW
          
  GatewayToInternet:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateway
      VpcId:
        Ref: MyVpc

  PublicSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVpc
      Tags:
      - Key: Name
        Value: Public-SubnetRT
          
  PublicSubnetRoute:
    Type: AWS::EC2::Route
    DependsOn: GatewayToInternet
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVpc
      CidrBlock:
        Ref: PublicSubnetCIDR
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: Public-Subnet
          
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicSubnetRouteTable
      SubnetId:
        Ref: PublicSubnet

  AZANatGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: GatewayToInternet
    Properties:
      Domain: Myvpc

  AZANatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - AZANatGatewayEIP
        - AllocationId
      SubnetId:
        Ref: PublicSubnet

  PrivateSubnetRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVpc
      Tags:
      - Key: Name
        Value: Private-Subnet-RT
          
  PrivateSubnetRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateSubnetRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: AZANatGateway

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: MyVpc
      CidrBlock:
        Ref: PrivateSubnetCIDR
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: Private-Subnet
        

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateSubnetRouteTable
      SubnetId:
        Ref: PrivateSubnet


  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      
      GroupDescription: My SG with port 22 and 8080 inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080          
          ToPort: 8080
          CidrIp: 0.0.0.0/0

      Tags:
        - Key: Name
          Value: EC2-SG
      VpcId: !Ref MyVpc  

Outputs:
  InternetGateway:
    Description: A reference to the IG
    Value:
      Ref: InternetGateway
  VPC:
    Description: A reference to the created VPC
    Value:
      Ref: MyVpc
  PublicSubnet:
    Description: A reference to the public subnet
    Value:
      Ref: PublicSubnet
  PrivateSubnet:
    Description: A reference to the private subnet
    Value:
      Ref: PrivateSubnet
