



AWSTemplateFormatVersion: '2010-09-09'
Description: Create Ec2 Machine and Rds

Parameters:
  AvailabilityZone:
    Type: String
    Description: select availability zone
    Default: us-west-1a

  AmiId:
    Type: String
    Description: The ID of the Instance
    Default: ami-00569e54da628d17c

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName

  DBInstanceIdentifier:
    Type: String
    Default: "webapp-database"

  DBUsername:
    Type: String
    NoEcho: "true"
    Description: Username for Mysql database access
    Default: "Mysqldb"
  DBPassword:
    NoEcho: "true"
    Description: Password Mysql database access
    Type: String
    MinLength: "8"
    MaxLength: "41"
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must contain only alphanumeric characters.

Resources:
  WebAppVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 192.168.0.0/16
      Tags:
        - Key: Name
          Value: RDSDEMOVPC

  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-west-1a
      VpcId:
        Ref: WebAppVpc
      CidrBlock: 192.168.1.0/24
      Tags:
        - Key: Name
          Value: Private-Subnet1

  PrivateSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: us-west-1c
      VpcId:
        Ref: WebAppVpc
      CidrBlock: 192.168.2.0/24
      Tags:
        - Key: Name
          Value: Private-Subnet2

  WebAppDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet for rds
      SubnetIds:
        - Ref: PrivateSubnet1
        - Ref: PrivateSubnet2
      Tags:
        - Key: Name
          Value: Rds-DBSubnetGroup

  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref AmiId
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
    


  WebAppDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBSubnetGroupName:
        Ref: WebAppDBSubnetGroup
      AllocatedStorage: "5"
      VpcSecurityGroups: !Ref WebAppSecurityGroup
      DBInstanceClass: db.t2.small
      Engine: MYSQL
      EngineVersion: 8.0.28
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Tags:
        - Key: Name
          Value: MyDBInstance

  
    
  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow HttPS and SSH and database"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
      VpcId: !Ref WebAppVpc


    

  WebAppEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref WebAppVpc
      InstanceId: !Ref WebAppInstance
      Tags:
        - Key: Name
          Value: EC2-EIP


