





AWSTemplateFormatVersion: '2010-09-09'
Description: Create Ec2 Machine and vpc

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Type: String
    Default: t2.micro
  
  ImageId:
    Type: String
    Default: ami-00569e54da628d17c
    
  MyAvailabilityZone:
    Description: Select the AZ
    Type: String
    Default: us-west-1a

  VpcCIDR:
    Type: String
    Description: Enter the IP range.
    Default: 10.0.0.0/16

  PublicSubnet1CIDR:
    Type: String
    Description: choose publicsubnetcidr
    Default: 10.0.0.0/24

  PrivateSubnetCIDR1:
    Type: String
    Description: Please enter the IP address range for the VPC subnet
    Default: 10.0.1.0/24

  PrivateSubnetCIDR2:
    Type: String
    Description: Please enter the IP address range for the VPC subnet
    Default: 10.0.2.0/24


  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String

  DBInstanceClass:
    Description: The database instance type
    Type: String
    Default: db.t2.small

  MultiAZ:
    Description: Multi-AZ master database
    Type: String
    Default: 'false'
    
  DBAllocatedStorage:
    Default: '5'
    Description: The size of the database (Gb)
     
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
       
      AvailabilityZone: !Ref MyAvailabilityZone
      SubnetId: !Ref PublicSubnet1

      Tags:
        - Key: Name
          Value: Demoec2  
  MyVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: Test-Vpc
  
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Test-IGW

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref MyVpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Ref PublicSubnet1CIDR
      AvailabilityZone: !Select [ 0, !GetAZs ]
      VpcId: !Ref MyVpc
      Tags:
         - Key: Name
           Value: Public-TestSubnet1

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVpc
      Tags:
        - Key: Name
          Value: Public-RouteTable

  Route: 
    DependsOn: InternetGatewayAttachment
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable  
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway 

  PublicSubnet1RoutetableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId:  !Ref PublicSubnet1


  AZANatGatewayEIP:
    Type: AWS::EC2::EIP
    DependsOn: InternetGateway
    Properties:
      Domain: Myvpc

  AZANatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - AZANatGatewayEIP
        - AllocationId
      SubnetId:
        Ref: PublicSubnet1

  PrivateSubnetRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVpc
      Tags:
      - Key: Name
        Value: Private-Subnet-RT1
          
  PrivateSubnetRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateSubnetRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: AZANatGateway

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-1a
      VpcId:
        Ref: MyVpc
      CidrBlock:
        Ref: PrivateSubnetCIDR1
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: Private-Subnet1
        

  PrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateSubnetRouteTable1
      SubnetId:
        Ref: PrivateSubnet


  PrivateSubnetRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: MyVpc
      Tags:
      - Key: Name
        Value: Private-Subnet-RT2
          
  PrivateSubnetRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PrivateSubnetRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId:
        Ref: AZANatGateway

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-1c
      VpcId:
        Ref: MyVpc
      CidrBlock:
        Ref: PrivateSubnetCIDR2
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: Private-Subnet2
        

  PrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PrivateSubnetRouteTable2
      SubnetId:
        Ref: PrivateSubnet2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      
      GroupDescription: My SG with port 22 and 8080 inbound
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080          
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306

      Tags:
        - Key: Name
          Value: EC2-SG
      VpcId: !Ref MyVpc  

  

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      Engine: MySQL
      EngineVersion: 5.5
      DBSecurityGroups: !Ref DBSecurityGroup
      DBSubnetGroup: 
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      MultiAZ: !Ref MultiAZ
       

  WebAppDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet for rds
      SubnetIds:
        - Ref: PrivateSubnet1
        - Ref: PrivateSubnet2
      Tags:
        - Key: Name
          Value: Rds-DBSubnetGroup
  
   #DBSecurityGroup:
    #Type: AWS::RDS::DBSecurityGroup
    #Properties:
     # DBSecurityGroupIngress:
       # EC2SecurityGroupName: !Ref WebAppSecurityGroup
      #GroupDescription: database access